### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by dev2games** [intrigus/gdx-freetype-gwt#4] opened 2018-05-19 00:20 UTC
Followed the directions provided, but getting this error: 

```
GwtApplication: exception: (InvalidStateError) : An attempt was made to use an object that is not, or is no longer, usable
```

This is the code that is causing the error. (When I revert this back to regular Bitmapfont instead of Freetype, the error goes away. So the error it definitely has to do with Freetype. 

```
package com.game.client.fonts;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.FreeTypeFontParameter;

/**
 * @author Nelson
 * Manages all game fonts
 */

public class GameFont {


    private FreeTypeFontGenerator generator;
    private BitmapFont font;


    /**
     * Game Fonts constructor
     *
     * @param fontFile the file location for the font file
     * @param size     the size of the font
     */

    public GameFont(String fontFile, int size) {
        generator = new FreeTypeFontGenerator(Gdx.files.internal("data/fonts/font.ttf"));
        FreeTypeFontParameter parameter = new FreeTypeFontParameter();
        parameter.size = 24;
        font = generator.generateFont(parameter);
        font.setColor(Color.YELLOW);
    }

    public BitmapFont getFont() {
        return font;
    }

    public FreeTypeFontGenerator getGenerator() {
        return generator;
    }

    public void setFont(BitmapFont font) {
        this.font = font;
    }

    public void dispose() {
        getFont().dispose();
        getGenerator().dispose();
    }

}
```

**Comment by intrigus** [comment] 2018-05-19 12:37
Do you have a self contained test case?

**Comment by chongbo2013** [comment] 2018-08-03 03:02
Hello mac mobile browser can not use, it will lead to a black screen

**Comment by dev2games** [comment] 2018-08-03 07:38
@chongbo2013 was tested on Windows browser. Non working :(

**Comment by intrigus** [comment] 2019-03-29 21:52
Closing as duplicate of https://github.com/intrigus/gdx-freetype-gwt/issues/7
since the root cause is probably the same.

**Closed by intrigus** 2019-03-29 21:52 UTC
Labels: bug, duplicate
