### ISSUE TITLE
InvalidStateError when using a font containing CJK characters.

### ISSUE THREAD

**Issue by GameJob** [intrigus/gdx-freetype-gwt#7] opened 2018-08-15 03:50 UTC
Gdx-freetype-gwt works fine if using western fonts.
However, it may throw InvalidStateError when using fonts containing CJK characters like DroidSansFallback.ttf or KaiGenGothicTW-Normal.ttf.

On Microsoft Edge, it works fine.

On Chrome, it displays "**Uncaught Error: java.lang.RuntimeException: com.google.gwt.core.client.JavaScriptException: (InvalidStateError) : Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.**"

On Firefox, it shows "**Error: java.lang.RuntimeException: com.google.gwt.core.client.JavaScriptException: (InvalidStateError) : An attempt was made to use an object that is not, or is no longer, usable**".

**Comment by intrigus** [comment] 2018-08-15 11:14
I know the cause, but it needs to be fixed in libgdx side.

**Comment by intrigus** [comment] 2019-08-20 20:54
Fixed :tada: in 4c0d121

**Closed by intrigus** 2019-08-20 20:54 UTC
Labels: bug
