### ISSUE TITLE
pls fix bug  Mac OS iphone  can not be used

### ISSUE THREAD

**Issue by chongbo2013** [intrigus/gdx-freetype-gwt#6] opened 2018-08-03 03:19 UTC
Because I don't know how to grab the mac os or Apple phone logs, but once I comment out the font-related code, I can run normally.
Online project urgent, ask for help

**Comment by chongbo2013** [comment] 2018-08-03 04:02
mac com.google.gwt.core.client.JavaScriptException(InvalidStateError) The object is in an ivalid state

**Comment by intrigus** [comment] 2019-03-29 21:52
Closing as duplicate of https://github.com/intrigus/gdx-freetype-gwt/issues/7
since the root cause is probably the same.

**Closed by intrigus** 2019-03-29 21:52 UTC
Labels: bug, duplicate
