### ISSUE TITLE
Font with shadows crashes

### ISSUE THREAD

**Issue by fgnm** [intrigus/gdx-freetype-gwt#9] opened 2020-05-17 10:40 UTC
When I set shadow parameters in `FreeTypeFontParameter` the app crashes.

Here is a sample code:
```Java
    private void createFonts() {
        FreeTypeFontGenerator.setMaxTextureSize(1024);

        FreeTypeFontGenerator fontGenerator = mAssetManager.get(mTextFontDesc);
        FreeTypeFontGenerator.FreeTypeFontParameter fontParameter;
        BitmapFont font;

        fontParameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
        fontParameter.size = 64;
        //fontParameter.shadowColor = Color.BLACK;
        //fontParameter.shadowOffsetX = 6;
        //fontParameter.shadowOffsetY = 6;
        fontParameter.genMipMaps = true;
        fontParameter.minFilter = Texture.TextureFilter.MipMapLinearNearest;
        fontParameter.magFilter = Texture.TextureFilter.MipMapLinearNearest;

        font = fontGenerator.generateFont(fontParameter);
        font.setUseIntegerPositions(true);

        mMainTitleFontStyle = new Label.LabelStyle(font, new Color(0xf9f901ff));
    }
```
If I uncomment any of `shadow` parameter GWT application crashes with the following error:
`Error: java.lang.RuntimeException: java.lang.ClassCastException`.

I'm really confused about that.. what could be the cause?

**Comment by intrigus** [comment] 2020-05-17 11:13
Please create a minimal runnable example.

**Comment by fgnm** [comment] 2020-05-17 12:07
Well, it is a very basic asset manager class:
```Java
public class Assets {
    private final AssetDescriptor<FreeTypeFontGenerator> mTextFontDesc = new AssetDescriptor<FreeTypeFontGenerator>("font/Mecha_Bold.ttf", FreeTypeFontGenerator.class);

    private AssetManager mAssetManager;
    public Label.LabelStyle mMainTitleFontStyle;

    public Assets() {
        mAssetManager = new AssetManager();
        mAssetManager.setLoader(FreeTypeFontGenerator.class, new FreeTypeFontGeneratorLoader(new InternalFileHandleResolver()));
        mAssetManager.setLoader(BitmapFont.class, ".ttf", new FreetypeFontLoader(new InternalFileHandleResolver()));
    }

    public void createAssets() {
        //Skip all other assets
        createFonts();
    }

    private void createFonts() {
        FreeTypeFontGenerator.setMaxTextureSize(1024);

        FreeTypeFontGenerator fontGenerator = mAssetManager.get(mTextFontDesc);
        FreeTypeFontGenerator.FreeTypeFontParameter fontParameter;
        BitmapFont font;

        fontParameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
        fontParameter.size = 64;
        //fontParameter.shadowColor = Color.BLACK;
        //fontParameter.shadowOffsetX = 6;
        //fontParameter.shadowOffsetY = 6;
        fontParameter.genMipMaps = true;
        fontParameter.minFilter = Texture.TextureFilter.MipMapLinearNearest;
        fontParameter.magFilter = Texture.TextureFilter.MipMapLinearNearest;

        font = fontGenerator.generateFont(fontParameter);
        font.setUseIntegerPositions(true);

        mMainTitleFontStyle = new Label.LabelStyle(font, new Color(0xf9f901ff));
    }

    public void dispose() {
        mAssetManager.dispose();
    }

    public boolean update() {
        return mAssetManager.update();
    }
}
```

Just create a new instance of `Assets`, call `mAssets.load()`, wait untile `mAssets.update()` becomes `true` and finally `mAssets.createAssets();`
On Android and iOS same code works fine.

**Comment by piotr-j** [comment] 2020-05-20 14:45
I can confirm that stuff explodes when shadow is set to something.

**Comment by intrigus** [comment] 2020-05-20 20:55
That's great to know that stuff explodes when shadows are used.
I'll look into it some time.

**Comment by intrigus** [comment] 2020-05-20 20:55
That's great to know that stuff explodes when shadows are used.
I'll look into it some time.

**Comment by piotr-j** [comment] 2020-05-20 21:27
Not very useful, I'm aware. Sadly the exception seems to occur in minified js code which makes it hard to debug. 
https://gist.github.com/piotr-j/136324b790406cda7eb4b8a9a0d23692
From https://github.com/piotr-j/skin-composer/tree/gwt

**Comment by intrigus** [comment] 2020-05-20 23:02
@piotr-j do you by chance have a runnable and web accessible gwt version?
Or could you provide a more debug friendly stacktrace?
(I currently haven't setup libgdx or gwt^^)

**Comment by piotr-j** [comment] 2020-05-21 08:40
Ill make one today. Is there more readable `freetype.js` somewhere?

**Comment by piotr-j** [comment] 2020-05-21 11:11
Runnable http://piotrjastrzebski.io/gwt-freetype-test/
Source https://github.com/piotr-j/gwt-freetype-test

**Comment by intrigus** [comment] 2020-05-21 20:35
Please try the new version "1.9.10.1" when it has reached maven central.
That may take up to one day.

Using your test it works.
@fgnm please confirm that it also works for you.

**Comment by piotr-j** [comment] 2020-05-22 17:47
`1.9.10.1` works, fantastic! How did you figure it out? Seems the cast was one of the issues, but i didnt get reasonable stacktraces for this...

**Comment by intrigus** [comment] 2020-05-23 10:51
I told eclipse to compile gwt using `-style PRETTY`.
That produced readable enough stacktraces.
As soon as I saw the code the problem was clear :)

Closing as fixed.

**Closed by intrigus** 2020-05-23 10:51 UTC
